// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

import type { Principal } from '@dfinity/principal';
import type { ActorMethod } from '@dfinity/agent';
import type { IDL } from '@dfinity/candid';

export interface Activity {
  'profile_image' : string,
  'element_id' : string,
  'activity_title' : string,
  'creator_id' : string,
  'link' : string,
  'creator_username' : string,
  'description' : string,
  'created_at' : bigint,
  'element_type' : string,
  'activity_image' : [] | [string],
}
export interface ClaimerInfo { 'principal' : Principal, 'amount' : bigint }
export interface CompleteSolutionData {
  'approved_pledges' : bigint,
  'features' : Array<IndexResponseBasicInfo>,
  'delivery_date' : bigint,
  'total_amount' : bigint,
  'feature_creators' : Array<ClaimerInfo>,
  'total_pledges' : bigint,
  'solution_provider' : ClaimerInfo,
  'feature_approval_counts' : Array<[string, bigint]>,
  'solution' : IndexResponseBasicInfo,
  'is_ready_for_completion' : boolean,
  'topic_owner' : ClaimerInfo,
  'approval_rate' : number,
  'platform_fee' : ClaimerInfo,
}
export interface CompletionResult {
  'completion_timestamp' : bigint,
  'transaction_blocks' : BigUint64Array | bigint[],
  'approval_rate' : number,
}
export interface EnrichedApprovalData {
  'status' : string,
  'approval_id' : string,
  'feature' : IndexResponseBasicInfo,
  'payment_type' : string,
  'pledge' : [] | [PledgeBasicInfo],
  'created_at' : bigint,
  'solution' : IndexResponseBasicInfo,
  'transaction_number' : bigint,
  'amount' : bigint,
}
export interface EnrichedPledgeData {
  'status' : string,
  'feature' : [] | [IndexResponseBasicInfo],
  'payment_type' : string,
  'idea' : IndexResponseBasicInfo,
  'expected_amount' : bigint,
  'pledge_id' : string,
  'created_at' : bigint,
  'amount_paid' : bigint,
  'amount' : bigint,
}
export interface Idea {
  'categories' : Array<string>,
  'title' : string,
  'description' : string,
  'videos' : Array<string>,
  'subtitle' : string,
  'images' : Array<string>,
}
export interface IndexResponse {
  'title' : string,
  'profile_image' : string,
  'element_id' : string,
  'description' : string,
  'total_pledged' : bigint,
  'reputation' : [] | [bigint],
  'element_type' : string,
  'subtitle' : string,
  'total_followers' : bigint,
  'creation_date' : bigint,
}
export interface IndexResponseBasicInfo {
  'title' : string,
  'profile_image' : string,
  'element_id' : string,
  'element_type' : string,
  'creation_date' : bigint,
}
export interface Milestone {
  'id' : bigint,
  'title' : string,
  'date' : bigint,
  'description' : string,
}
export interface Notification {
  'title' : string,
  'linkURL' : string,
  'read' : boolean,
  'typeOf' : string,
  'description' : string,
  'sender' : string,
  'imageURL' : string,
  'subtitle' : string,
}
export type PaymentType = { 'Fiat' : null } |
  { 'Crypto' : null };
export interface PledgeApproval {
  'pledge_id' : string,
  'transaction_number' : bigint,
  'amount' : bigint,
}
export interface PledgeBasicInfo {
  'status' : string,
  'feature_id' : [] | [string],
  'pledge_id' : string,
  'idea_id' : string,
  'amount' : bigint,
}
export interface PledgeData {
  'status' : string,
  'feature_id' : [] | [string],
  'payment_type' : string,
  'expected_amount' : bigint,
  'user' : string,
  'idea_id' : string,
  'target' : string,
  'amount_paid' : bigint,
  'amount' : bigint,
  'doc_key' : string,
}
export interface Product {
  'owner' : [] | [Principal],
  'link' : string,
  'name' : string,
  'description' : string,
  'score' : [] | [number],
  'company' : [] | [string],
  'image' : [] | [string],
}
export type Result = { 'Ok' : string } |
  { 'Err' : string };
export type Result_1 = { 'Ok' : Array<string> } |
  { 'Err' : string };
export type Result_10 = { 'Ok' : [Array<Activity>, bigint, bigint, bigint] } |
  { 'Err' : string };
export type Result_11 = { 'Ok' : CompleteSolutionData } |
  { 'Err' : string };
export type Result_12 = { 'Ok' : [bigint, bigint] } |
  { 'Err' : string };
export type Result_13 = { 'Ok' : Array<PledgeData> } |
  { 'Err' : string };
export type Result_14 = { 'Ok' : Array<EnrichedApprovalData> } |
  { 'Err' : string };
export type Result_15 = { 'Ok' : UserBasicInfo } |
  { 'Err' : string };
export type Result_16 = { 'Ok' : Array<EnrichedPledgeData> } |
  { 'Err' : string };
export type Result_2 = { 'Ok' : null } |
  { 'Err' : string };
export type Result_3 = { 'Ok' : BigUint64Array | bigint[] } |
  { 'Err' : string };
export type Result_4 = { 'Ok' : CompletionResult } |
  { 'Err' : string };
export type Result_5 = { 'Ok' : bigint } |
  { 'Err' : string };
export type Result_6 = {
    'Ok' : [bigint, bigint, bigint, Array<[string, string]>]
  } |
  { 'Err' : string };
export type Result_7 = { 'Ok' : Array<UserProfileBasicInfo> } |
  { 'Err' : string };
export type Result_8 = {
    'Ok' : [Array<IndexResponseBasicInfo>, bigint, bigint, bigint]
  } |
  { 'Err' : string };
export type Result_9 = {
    'Ok' : [Array<IndexResponse>, bigint, bigint, bigint]
  } |
  { 'Err' : string };
export interface SetIdea { 'key' : string, 'idea' : Idea }
export interface Solution {
  'categories' : Array<string>,
  'title' : string,
  'features' : Array<string>,
  'description' : string,
  'videos' : Array<string>,
  'subtitle' : string,
  'milestones' : Array<Milestone>,
  'images' : Array<string>,
}
export interface UserBasicInfo {
  'username' : string,
  'profile_picture' : string,
  'active_pledged' : bigint,
  'background_image' : string,
  'description' : string,
  'total_pledged' : bigint,
  'followings_count' : bigint,
  'reputation' : bigint,
  'user_id' : string,
  'followers_count' : bigint,
}
export interface UserProfileBasicInfo {
  'username' : string,
  'profile_picture' : string,
  'user_id' : string,
}
export interface _SERVICE {
  'approve_pledge' : ActorMethod<
    [string, string, bigint, bigint, PaymentType],
    Result
  >,
  'approve_solution_pledges' : ActorMethod<
    [string, PaymentType, Array<PledgeApproval>],
    Result_1
  >,
  'build_version' : ActorMethod<[], string>,
  'cancel_pledge' : ActorMethod<[string], Result_2>,
  'check_cycles' : ActorMethod<[], bigint>,
  'claim_tokens' : ActorMethod<[string], Result_3>,
  'complete_solution' : ActorMethod<[string], Result_4>,
  'create_ideas' : ActorMethod<[Array<SetIdea>, string], Result_2>,
  'create_new_product' : ActorMethod<[Product, string], Result_2>,
  'create_or_update_idea' : ActorMethod<[string, Idea, string], Result_2>,
  'create_or_update_solution' : ActorMethod<
    [string, Solution, string],
    Result_2
  >,
  'create_or_update_topic' : ActorMethod<[string, Idea], Result_2>,
  'delete_many_images' : ActorMethod<[string, Array<string>], Result>,
  'delete_pledge' : ActorMethod<[string], Result_2>,
  'eliminate_idea' : ActorMethod<[string], Result_2>,
  'eliminate_solution' : ActorMethod<[string], Result_2>,
  'eliminate_topic' : ActorMethod<[string], Result_2>,
  'get_available_balance' : ActorMethod<[string], Result_5>,
  'get_feature_subaccount_balance' : ActorMethod<[string], Result_5>,
  'get_funding_details' : ActorMethod<[string, string], Result_6>,
  'get_historical_pledged_balance' : ActorMethod<[string], Result_5>,
  'get_paginated_common_users' : ActorMethod<
    [string, string, [] | [bigint], [] | [bigint]],
    Result_7
  >,
  'get_paginated_followers' : ActorMethod<
    [string, [] | [bigint], [] | [bigint]],
    Result_8
  >,
  'get_paginated_following_elements' : ActorMethod<
    [string, [] | [bigint], [] | [bigint]],
    Result_8
  >,
  'get_paginated_ideas' : ActorMethod<
    [string, [] | [bigint], [] | [bigint], [] | [string], [] | [string]],
    Result_9
  >,
  'get_paginated_ideas_by_solution' : ActorMethod<
    [string, [] | [bigint], [] | [bigint], [] | [string], string],
    Result_9
  >,
  'get_paginated_most_recent_activities' : ActorMethod<
    [string, [] | [bigint], [] | [bigint]],
    Result_10
  >,
  'get_paginated_topics' : ActorMethod<
    [string, [] | [bigint], [] | [bigint], [] | [string]],
    Result_9
  >,
  'get_paginated_topics_ideas' : ActorMethod<
    [string, [] | [bigint], [] | [bigint], [] | [string]],
    Result_9
  >,
  'get_paginated_users' : ActorMethod<
    [string, [] | [bigint], [] | [bigint], [] | [string]],
    Result_9
  >,
  'get_pledged_balance' : ActorMethod<[string], Result_5>,
  'get_solution_completion_data' : ActorMethod<[string], Result_11>,
  'get_total_followers' : ActorMethod<[string], bigint>,
  'get_total_following' : ActorMethod<[string], bigint>,
  'get_total_pledged' : ActorMethod<[string, string], Result_5>,
  'get_total_pledged_and_expected' : ActorMethod<[string, string], Result_12>,
  'get_user_active_pledges' : ActorMethod<[string], Result_13>,
  'get_user_approvals_enriched' : ActorMethod<[string], Result_14>,
  'get_user_basic_information' : ActorMethod<[string], Result_15>,
  'get_user_pledges_enriched' : ActorMethod<[string], Result_16>,
  'get_user_pledges_for_solution' : ActorMethod<[string, string], Result_16>,
  'get_user_profile_pic' : ActorMethod<[string], string>,
  'get_user_real_balance' : ActorMethod<[string], Result_5>,
  'get_user_reputation' : ActorMethod<[Principal], Result_5>,
  'get_user_total_pledges' : ActorMethod<[string], Result_13>,
  'get_user_username' : ActorMethod<[string], string>,
  'pledge_create' : ActorMethod<
    [string, string, string, bigint, Uint8Array | number[]],
    string
  >,
  'query_scheduled_tasks_state' : ActorMethod<[], string>,
  'reject_approval' : ActorMethod<[string, string, [] | [string]], Result_2>,
  'reverse_approval' : ActorMethod<[string], Result_2>,
  'send_single_notification' : ActorMethod<
    [string, string, Notification],
    Result_2
  >,
  'start_scheduled_tasks' : ActorMethod<[], string>,
  'stop_scheduled_tasks' : ActorMethod<[], string>,
  'trigger_delete_orphan_ideas' : ActorMethod<[], Result_2>,
  'trigger_delete_orphan_solutions' : ActorMethod<[], Result_2>,
  'trigger_delete_unused_images' : ActorMethod<[], Result_2>,
  'upload_image' : ActorMethod<
    [string, string, Uint8Array | number[], string, string, string],
    Result
  >,
  'validate_user_balance_or_delete_pledge' : ActorMethod<
    [string, bigint, string],
    Result_2
  >,
  'withdraw_approval' : ActorMethod<[string], Result_5>,
  'withdraw_from_feature_subaccount' : ActorMethod<
    [bigint, string, Principal],
    Result_5
  >,
  'withdraw_rejection' : ActorMethod<[string, string], Result_2>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];