// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

export const idlFactory = ({ IDL }) => {
  const Idea = IDL.Record({
    'categories' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'description' : IDL.Text,
    'videos' : IDL.Vec(IDL.Text),
    'subtitle' : IDL.Text,
    'images' : IDL.Vec(IDL.Text),
  });
  const SetIdea = IDL.Record({ 'key' : IDL.Text, 'idea' : Idea });
  const Result = IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text });
  const Product = IDL.Record({
    'owner' : IDL.Opt(IDL.Principal),
    'link' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'score' : IDL.Opt(IDL.Nat8),
    'company' : IDL.Opt(IDL.Text),
    'image' : IDL.Opt(IDL.Text),
  });
  const Milestone = IDL.Record({
    'id' : IDL.Nat64,
    'title' : IDL.Text,
    'date' : IDL.Nat64,
    'description' : IDL.Text,
  });
  const Solution = IDL.Record({
    'categories' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'videos' : IDL.Vec(IDL.Text),
    'subtitle' : IDL.Text,
    'milestones' : IDL.Vec(Milestone),
    'images' : IDL.Vec(IDL.Text),
  });
  const Result_1 = IDL.Variant({ 'Ok' : IDL.Text, 'Err' : IDL.Text });
  const Result_2 = IDL.Variant({ 'Ok' : IDL.Nat64, 'Err' : IDL.Text });
  const Result_3 = IDL.Variant({
    'Ok' : IDL.Tuple(
      IDL.Nat64,
      IDL.Nat64,
      IDL.Nat64,
      IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    ),
    'Err' : IDL.Text,
  });
  const IndexResponse = IDL.Record({
    'title' : IDL.Text,
    'profile_image' : IDL.Text,
    'element_id' : IDL.Text,
    'description' : IDL.Text,
    'total_pledged' : IDL.Nat64,
    'reputation' : IDL.Opt(IDL.Nat64),
    'element_type' : IDL.Text,
    'subtitle' : IDL.Text,
    'total_followers' : IDL.Nat64,
    'creation_date' : IDL.Nat64,
  });
  const Result_4 = IDL.Variant({
    'Ok' : IDL.Tuple(IDL.Vec(IndexResponse), IDL.Nat64, IDL.Nat64, IDL.Nat64),
    'Err' : IDL.Text,
  });
  const Result_5 = IDL.Variant({
    'Ok' : IDL.Tuple(IDL.Nat64, IDL.Nat64),
    'Err' : IDL.Text,
  });
  const PledgeData = IDL.Record({
    'feature_id' : IDL.Opt(IDL.Text),
    'expected_amount' : IDL.Nat64,
    'user' : IDL.Text,
    'idea_id' : IDL.Text,
    'target' : IDL.Text,
    'amount' : IDL.Nat64,
    'doc_key' : IDL.Text,
  });
  const Result_6 = IDL.Variant({
    'Ok' : IDL.Vec(PledgeData),
    'Err' : IDL.Text,
  });
  const Notification = IDL.Record({
    'title' : IDL.Text,
    'linkURL' : IDL.Text,
    'read' : IDL.Bool,
    'typeOf' : IDL.Text,
    'description' : IDL.Text,
    'sender' : IDL.Text,
    'imageURL' : IDL.Text,
    'subtitle' : IDL.Text,
  });
  return IDL.Service({
    'build_version' : IDL.Func([], [IDL.Text], ['query']),
    'create_ideas' : IDL.Func([IDL.Vec(SetIdea), IDL.Text], [Result], []),
    'create_new_product' : IDL.Func([Product, IDL.Text], [Result], []),
    'create_or_update_idea' : IDL.Func(
        [IDL.Text, Idea, IDL.Text],
        [Result],
        [],
      ),
    'create_or_update_solution' : IDL.Func(
        [IDL.Text, Solution, IDL.Text],
        [Result],
        [],
      ),
    'create_or_update_topic' : IDL.Func([IDL.Text, Idea], [Result], []),
    'delete_many_images' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [Result_1],
        [],
      ),
    'delete_pledge' : IDL.Func([IDL.Text], [Result], []),
    'eliminate_idea' : IDL.Func([IDL.Text], [Result], []),
    'eliminate_solution' : IDL.Func([IDL.Text], [Result], []),
    'eliminate_topic' : IDL.Func([IDL.Text], [Result], []),
    'get_available_balance' : IDL.Func([IDL.Text], [Result_2], []),
    'get_funding_details' : IDL.Func(
        [IDL.Text, IDL.Text],
        [Result_3],
        ['query'],
      ),
    'get_paginated_ideas' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Nat64),
          IDL.Opt(IDL.Nat64),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [Result_4],
        ['query'],
      ),
    'get_paginated_ideas_by_solution' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Nat64),
          IDL.Opt(IDL.Nat64),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [Result_4],
        ['query'],
      ),
    'get_paginated_topics' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat64), IDL.Opt(IDL.Nat64), IDL.Opt(IDL.Text)],
        [Result_4],
        ['query'],
      ),
    'get_paginated_topics_ideas' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat64), IDL.Opt(IDL.Nat64), IDL.Opt(IDL.Text)],
        [Result_4],
        ['query'],
      ),
    'get_paginated_users' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat64), IDL.Opt(IDL.Nat64), IDL.Opt(IDL.Text)],
        [Result_4],
        ['query'],
      ),
    'get_pledged_balance' : IDL.Func([IDL.Text], [Result_2], ['query']),
    'get_total_followers' : IDL.Func([IDL.Text], [IDL.Nat64], ['query']),
    'get_total_pledged' : IDL.Func([IDL.Text, IDL.Text], [Result_2], ['query']),
    'get_total_pledged_and_expected' : IDL.Func(
        [IDL.Text, IDL.Text],
        [Result_5],
        ['query'],
      ),
    'get_user_active_pledges' : IDL.Func([IDL.Text], [Result_6], ['query']),
    'get_user_profile_pic' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'get_user_real_balance' : IDL.Func([IDL.Text], [Result_2], []),
    'get_user_reputation' : IDL.Func([IDL.Principal], [Result_2], ['query']),
    'get_user_username' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'pledge_create' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat64, IDL.Vec(IDL.Nat8)],
        [IDL.Text],
        [],
      ),
    'query_scheduled_tasks_state' : IDL.Func([], [IDL.Text], ['query']),
    'send_single_notification' : IDL.Func(
        [IDL.Text, IDL.Text, Notification],
        [Result],
        [],
      ),
    'start_scheduled_tasks' : IDL.Func([], [IDL.Text], []),
    'stop_scheduled_tasks' : IDL.Func([], [IDL.Text], []),
    'trigger_delete_orphan_ideas' : IDL.Func([], [Result], []),
    'trigger_delete_orphan_solutions' : IDL.Func([], [Result], []),
    'trigger_delete_unused_images' : IDL.Func([], [Result], []),
    'upload_image' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8), IDL.Text, IDL.Text, IDL.Text],
        [Result_1],
        [],
      ),
    'validate_user_balance_or_delete_pledge' : IDL.Func(
        [IDL.Text, IDL.Nat64, IDL.Text],
        [Result],
        [],
      ),
  });
};
export const init = ({ IDL }) => { return []; };