// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

export const idlFactory = ({ IDL }) => {
  const Idea = IDL.Record({
    'categories' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'description' : IDL.Text,
    'videos' : IDL.Vec(IDL.Text),
    'subtitle' : IDL.Text,
    'images' : IDL.Vec(IDL.Text),
  });
  const SetIdea = IDL.Record({ 'key' : IDL.Text, 'idea' : Idea });
  const Result = IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text });
  const Product = IDL.Record({
    'owner' : IDL.Opt(IDL.Principal),
    'link' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'score' : IDL.Opt(IDL.Nat8),
    'company' : IDL.Opt(IDL.Text),
    'image' : IDL.Opt(IDL.Text),
  });
  const Milestone = IDL.Record({
    'id' : IDL.Nat64,
    'title' : IDL.Text,
    'date' : IDL.Nat64,
    'description' : IDL.Text,
  });
  const Solution = IDL.Record({
    'categories' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'videos' : IDL.Vec(IDL.Text),
    'subtitle' : IDL.Text,
    'milestones' : IDL.Vec(Milestone),
    'images' : IDL.Vec(IDL.Text),
  });
  const Result_1 = IDL.Variant({ 'Ok' : IDL.Text, 'Err' : IDL.Text });
  const Result_2 = IDL.Variant({ 'Ok' : IDL.Nat64, 'Err' : IDL.Text });
  const PledgeData = IDL.Record({
    'feature_id' : IDL.Opt(IDL.Text),
    'expected_amount' : IDL.Nat64,
    'user' : IDL.Text,
    'idea_id' : IDL.Text,
    'target' : IDL.Text,
    'amount' : IDL.Nat64,
    'doc_key' : IDL.Text,
  });
  const Result_3 = IDL.Variant({
    'Ok' : IDL.Vec(PledgeData),
    'Err' : IDL.Text,
  });
  return IDL.Service({
    'build_version' : IDL.Func([], [IDL.Text], ['query']),
    'create_ideas' : IDL.Func([IDL.Vec(SetIdea), IDL.Text], [Result], []),
    'create_new_product' : IDL.Func([Product, IDL.Text], [Result], []),
    'create_or_update_idea' : IDL.Func(
        [IDL.Text, Idea, IDL.Text],
        [Result],
        [],
      ),
    'create_or_update_solution' : IDL.Func(
        [IDL.Text, Solution, IDL.Text],
        [Result],
        [],
      ),
    'create_or_update_topic' : IDL.Func([IDL.Text, Idea], [Result], []),
    'delete_many_images' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [Result_1],
        [],
      ),
    'delete_pledge' : IDL.Func([IDL.Text], [Result], []),
    'eliminate_idea' : IDL.Func([IDL.Text], [Result], []),
    'eliminate_solution' : IDL.Func([IDL.Text], [Result], []),
    'eliminate_topic' : IDL.Func([IDL.Text], [Result], []),
    'get_pledged_balance' : IDL.Func([IDL.Text], [Result_2], ['query']),
    'get_user_active_pledges' : IDL.Func([IDL.Text], [Result_3], ['query']),
    'query_scheduled_tasks_state' : IDL.Func([], [IDL.Text], ['query']),
    'start_scheduled_tasks' : IDL.Func([], [IDL.Text], []),
    'stop_scheduled_tasks' : IDL.Func([], [IDL.Text], []),
    'trigger_delete_orphan_ideas' : IDL.Func([], [Result], []),
    'trigger_delete_orphan_solutions' : IDL.Func([], [Result], []),
    'trigger_delete_unused_images' : IDL.Func([], [Result], []),
    'upload_image' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8), IDL.Text, IDL.Text, IDL.Text],
        [Result_1],
        [],
      ),
  });
};
export const init = ({ IDL }) => { return []; };