// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

import type {_SERVICE as SatelliteActor, Idea, IndexResponse, Milestone, Notification, PledgeData, Product, SetIdea, Solution, Result, Result_1, Result_2, Result_3, Result_4} from './satellite.did';
import {idlFactory} from './satellite.factory.did.js';
import {getSatelliteExtendedActor} from '@junobuild/core-peer';

export const buildVersion = async (): Promise<string> => {
	const {build_version} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await build_version();
}

export const createIdeas = async (value0: Array, value1: string): Promise<Result> => {
	const {create_ideas} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await create_ideas(value0, value1);
}

export const createNewProduct = async (value0: Product, value1: string): Promise<Result> => {
	const {create_new_product} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await create_new_product(value0, value1);
}

export const createOrUpdateIdea = async (value0: string, value1: Idea, value2: string): Promise<Result> => {
	const {create_or_update_idea} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await create_or_update_idea(value0, value1, value2);
}

export const createOrUpdateSolution = async (value0: string, value1: Solution, value2: string): Promise<Result> => {
	const {create_or_update_solution} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await create_or_update_solution(value0, value1, value2);
}

export const createOrUpdateTopic = async (value0: string, value1: Idea): Promise<Result> => {
	const {create_or_update_topic} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await create_or_update_topic(value0, value1);
}

export const deleteManyImages = async (value0: string, value1: Array): Promise<Result_1> => {
	const {delete_many_images} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await delete_many_images(value0, value1);
}

export const deletePledge = async (value0: string): Promise<Result> => {
	const {delete_pledge} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await delete_pledge(value0);
}

export const eliminateIdea = async (value0: string): Promise<Result> => {
	const {eliminate_idea} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await eliminate_idea(value0);
}

export const eliminateSolution = async (value0: string): Promise<Result> => {
	const {eliminate_solution} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await eliminate_solution(value0);
}

export const eliminateTopic = async (value0: string): Promise<Result> => {
	const {eliminate_topic} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await eliminate_topic(value0);
}

export const getAvailableBalance = async (value0: string): Promise<Result_2> => {
	const {get_available_balance} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await get_available_balance(value0);
}

export const getPaginatedIdeas = async (value0: string, value1: unknown, value2: unknown, value3: unknown, value4: unknown): Promise<Result_3> => {
	const {get_paginated_ideas} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await get_paginated_ideas(value0, value1, value2, value3, value4);
}

export const getPaginatedTopics = async (value0: string, value1: unknown, value2: unknown, value3: unknown): Promise<Result_3> => {
	const {get_paginated_topics} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await get_paginated_topics(value0, value1, value2, value3);
}

export const getPaginatedUsers = async (value0: string, value1: unknown, value2: unknown, value3: unknown): Promise<Result_3> => {
	const {get_paginated_users} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await get_paginated_users(value0, value1, value2, value3);
}

export const getPledgedBalance = async (value0: string): Promise<Result_2> => {
	const {get_pledged_balance} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await get_pledged_balance(value0);
}

export const getTotalFollowers = async (value0: string): Promise<bigint> => {
	const {get_total_followers} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await get_total_followers(value0);
}

export const getTotalPledged = async (value0: string, value1: string): Promise<Result_2> => {
	const {get_total_pledged} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await get_total_pledged(value0, value1);
}

export const getUserActivePledges = async (value0: string): Promise<Result_4> => {
	const {get_user_active_pledges} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await get_user_active_pledges(value0);
}

export const getUserProfilePic = async (value0: string): Promise<string> => {
	const {get_user_profile_pic} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await get_user_profile_pic(value0);
}

export const getUserRealBalance = async (value0: string): Promise<Result_2> => {
	const {get_user_real_balance} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await get_user_real_balance(value0);
}

export const getUserReputation = async (value0: Principal): Promise<Result_2> => {
	const {get_user_reputation} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await get_user_reputation(value0);
}

export const getUserUsername = async (value0: string): Promise<string> => {
	const {get_user_username} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await get_user_username(value0);
}

export const pledgeCreate = async (value0: string, value1: string, value2: string, value3: bigint, value4: unknown): Promise<string> => {
	const {pledge_create} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await pledge_create(value0, value1, value2, value3, value4);
}

export const queryScheduledTasksState = async (): Promise<string> => {
	const {query_scheduled_tasks_state} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await query_scheduled_tasks_state();
}

export const sendSingleNotification = async (value0: string, value1: string, value2: Notification): Promise<Result> => {
	const {send_single_notification} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await send_single_notification(value0, value1, value2);
}

export const startScheduledTasks = async (): Promise<string> => {
	const {start_scheduled_tasks} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await start_scheduled_tasks();
}

export const stopScheduledTasks = async (): Promise<string> => {
	const {stop_scheduled_tasks} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await stop_scheduled_tasks();
}

export const triggerDeleteOrphanIdeas = async (): Promise<Result> => {
	const {trigger_delete_orphan_ideas} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await trigger_delete_orphan_ideas();
}

export const triggerDeleteOrphanSolutions = async (): Promise<Result> => {
	const {trigger_delete_orphan_solutions} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await trigger_delete_orphan_solutions();
}

export const triggerDeleteUnusedImages = async (): Promise<Result> => {
	const {trigger_delete_unused_images} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await trigger_delete_unused_images();
}

export const uploadImage = async (value0: string, value1: string, value2: unknown, value3: string, value4: string, value5: string): Promise<Result_1> => {
	const {upload_image} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await upload_image(value0, value1, value2, value3, value4, value5);
}

export const validateUserBalanceOrDeletePledge = async (value0: string, value1: bigint, value2: string): Promise<Result> => {
	const {validate_user_balance_or_delete_pledge} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await validate_user_balance_or_delete_pledge(value0, value1, value2);
}