// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

export const idlFactory = ({ IDL }) => {
  const PaymentType = IDL.Variant({ 'Fiat' : IDL.Null, 'Crypto' : IDL.Null });
  const Result = IDL.Variant({ 'Ok' : IDL.Text, 'Err' : IDL.Text });
  const PledgeApproval = IDL.Record({
    'pledge_id' : IDL.Text,
    'transaction_number' : IDL.Nat64,
    'amount' : IDL.Nat64,
  });
  const Result_1 = IDL.Variant({ 'Ok' : IDL.Vec(IDL.Text), 'Err' : IDL.Text });
  const Result_2 = IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text });
  const Idea = IDL.Record({
    'categories' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'description' : IDL.Text,
    'videos' : IDL.Vec(IDL.Text),
    'subtitle' : IDL.Text,
    'images' : IDL.Vec(IDL.Text),
  });
  const SetIdea = IDL.Record({ 'key' : IDL.Text, 'idea' : Idea });
  const Product = IDL.Record({
    'owner' : IDL.Opt(IDL.Principal),
    'link' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'score' : IDL.Opt(IDL.Nat8),
    'company' : IDL.Opt(IDL.Text),
    'image' : IDL.Opt(IDL.Text),
  });
  const Milestone = IDL.Record({
    'id' : IDL.Nat64,
    'title' : IDL.Text,
    'date' : IDL.Nat64,
    'description' : IDL.Text,
  });
  const Solution = IDL.Record({
    'categories' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'videos' : IDL.Vec(IDL.Text),
    'subtitle' : IDL.Text,
    'milestones' : IDL.Vec(Milestone),
    'images' : IDL.Vec(IDL.Text),
  });
  const Result_3 = IDL.Variant({ 'Ok' : IDL.Nat64, 'Err' : IDL.Text });
  const Result_4 = IDL.Variant({
    'Ok' : IDL.Tuple(
      IDL.Nat64,
      IDL.Nat64,
      IDL.Nat64,
      IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    ),
    'Err' : IDL.Text,
  });
  const UserProfileBasicInfo = IDL.Record({
    'username' : IDL.Text,
    'profile_picture' : IDL.Text,
    'user_id' : IDL.Text,
  });
  const Result_5 = IDL.Variant({
    'Ok' : IDL.Vec(UserProfileBasicInfo),
    'Err' : IDL.Text,
  });
  const IndexResponseBasicInfo = IDL.Record({
    'title' : IDL.Text,
    'profile_image' : IDL.Text,
    'element_id' : IDL.Text,
    'element_type' : IDL.Text,
    'creation_date' : IDL.Nat64,
  });
  const Result_6 = IDL.Variant({
    'Ok' : IDL.Tuple(
      IDL.Vec(IndexResponseBasicInfo),
      IDL.Nat64,
      IDL.Nat64,
      IDL.Nat64,
    ),
    'Err' : IDL.Text,
  });
  const IndexResponse = IDL.Record({
    'title' : IDL.Text,
    'profile_image' : IDL.Text,
    'element_id' : IDL.Text,
    'description' : IDL.Text,
    'total_pledged' : IDL.Nat64,
    'reputation' : IDL.Opt(IDL.Nat64),
    'element_type' : IDL.Text,
    'subtitle' : IDL.Text,
    'total_followers' : IDL.Nat64,
    'creation_date' : IDL.Nat64,
  });
  const Result_7 = IDL.Variant({
    'Ok' : IDL.Tuple(IDL.Vec(IndexResponse), IDL.Nat64, IDL.Nat64, IDL.Nat64),
    'Err' : IDL.Text,
  });
  const Activity = IDL.Record({
    'profile_image' : IDL.Text,
    'element_id' : IDL.Text,
    'activity_title' : IDL.Text,
    'creator_id' : IDL.Text,
    'link' : IDL.Text,
    'creator_username' : IDL.Text,
    'description' : IDL.Text,
    'created_at' : IDL.Nat64,
    'element_type' : IDL.Text,
    'activity_image' : IDL.Opt(IDL.Text),
  });
  const Result_8 = IDL.Variant({
    'Ok' : IDL.Tuple(IDL.Vec(Activity), IDL.Nat64, IDL.Nat64, IDL.Nat64),
    'Err' : IDL.Text,
  });
  const Result_9 = IDL.Variant({
    'Ok' : IDL.Tuple(IDL.Nat64, IDL.Nat64),
    'Err' : IDL.Text,
  });
  const PledgeData = IDL.Record({
    'status' : IDL.Text,
    'feature_id' : IDL.Opt(IDL.Text),
    'payment_type' : IDL.Text,
    'expected_amount' : IDL.Nat64,
    'user' : IDL.Text,
    'idea_id' : IDL.Text,
    'target' : IDL.Text,
    'amount_paid' : IDL.Nat64,
    'amount' : IDL.Nat64,
    'doc_key' : IDL.Text,
  });
  const Result_10 = IDL.Variant({
    'Ok' : IDL.Vec(PledgeData),
    'Err' : IDL.Text,
  });
  const UserBasicInfo = IDL.Record({
    'username' : IDL.Text,
    'profile_picture' : IDL.Text,
    'active_pledged' : IDL.Nat64,
    'background_image' : IDL.Text,
    'description' : IDL.Text,
    'total_pledged' : IDL.Nat64,
    'followings_count' : IDL.Nat64,
    'reputation' : IDL.Nat64,
    'user_id' : IDL.Text,
    'followers_count' : IDL.Nat64,
  });
  const Result_11 = IDL.Variant({ 'Ok' : UserBasicInfo, 'Err' : IDL.Text });
  const EnrichedPledgeData = IDL.Record({
    'status' : IDL.Text,
    'feature' : IDL.Opt(IndexResponseBasicInfo),
    'payment_type' : IDL.Text,
    'idea' : IndexResponseBasicInfo,
    'expected_amount' : IDL.Nat64,
    'pledge_id' : IDL.Text,
    'created_at' : IDL.Nat64,
    'amount_paid' : IDL.Nat64,
    'amount' : IDL.Nat64,
  });
  const Result_12 = IDL.Variant({
    'Ok' : IDL.Vec(EnrichedPledgeData),
    'Err' : IDL.Text,
  });
  const Notification = IDL.Record({
    'title' : IDL.Text,
    'linkURL' : IDL.Text,
    'read' : IDL.Bool,
    'typeOf' : IDL.Text,
    'description' : IDL.Text,
    'sender' : IDL.Text,
    'imageURL' : IDL.Text,
    'subtitle' : IDL.Text,
  });
  return IDL.Service({
    'approve_pledge' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat64, IDL.Nat64, PaymentType],
        [Result],
        [],
      ),
    'approve_solution_pledges' : IDL.Func(
        [IDL.Text, PaymentType, IDL.Vec(PledgeApproval)],
        [Result_1],
        [],
      ),
    'build_version' : IDL.Func([], [IDL.Text], ['query']),
    'cancel_pledge' : IDL.Func([IDL.Text], [Result_2], []),
    'check_cycles' : IDL.Func([], [IDL.Nat], ['query']),
    'create_ideas' : IDL.Func([IDL.Vec(SetIdea), IDL.Text], [Result_2], []),
    'create_new_product' : IDL.Func([Product, IDL.Text], [Result_2], []),
    'create_or_update_idea' : IDL.Func(
        [IDL.Text, Idea, IDL.Text],
        [Result_2],
        [],
      ),
    'create_or_update_solution' : IDL.Func(
        [IDL.Text, Solution, IDL.Text],
        [Result_2],
        [],
      ),
    'create_or_update_topic' : IDL.Func([IDL.Text, Idea], [Result_2], []),
    'delete_many_images' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [Result],
        [],
      ),
    'delete_pledge' : IDL.Func([IDL.Text], [Result_2], []),
    'eliminate_idea' : IDL.Func([IDL.Text], [Result_2], []),
    'eliminate_solution' : IDL.Func([IDL.Text], [Result_2], []),
    'eliminate_topic' : IDL.Func([IDL.Text], [Result_2], []),
    'get_available_balance' : IDL.Func([IDL.Text], [Result_3], []),
    'get_feature_subaccount_balance' : IDL.Func([IDL.Text], [Result_3], []),
    'get_funding_details' : IDL.Func(
        [IDL.Text, IDL.Text],
        [Result_4],
        ['query'],
      ),
    'get_historical_pledged_balance' : IDL.Func(
        [IDL.Text],
        [Result_3],
        ['query'],
      ),
    'get_paginated_common_users' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat64), IDL.Opt(IDL.Nat64)],
        [Result_5],
        ['query'],
      ),
    'get_paginated_followers' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat64), IDL.Opt(IDL.Nat64)],
        [Result_6],
        ['query'],
      ),
    'get_paginated_following_elements' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat64), IDL.Opt(IDL.Nat64)],
        [Result_6],
        ['query'],
      ),
    'get_paginated_ideas' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Nat64),
          IDL.Opt(IDL.Nat64),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [Result_7],
        ['query'],
      ),
    'get_paginated_ideas_by_solution' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Nat64),
          IDL.Opt(IDL.Nat64),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [Result_7],
        ['query'],
      ),
    'get_paginated_most_recent_activities' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat64), IDL.Opt(IDL.Nat64)],
        [Result_8],
        ['query'],
      ),
    'get_paginated_topics' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat64), IDL.Opt(IDL.Nat64), IDL.Opt(IDL.Text)],
        [Result_7],
        ['query'],
      ),
    'get_paginated_topics_ideas' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat64), IDL.Opt(IDL.Nat64), IDL.Opt(IDL.Text)],
        [Result_7],
        ['query'],
      ),
    'get_paginated_users' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat64), IDL.Opt(IDL.Nat64), IDL.Opt(IDL.Text)],
        [Result_7],
        ['query'],
      ),
    'get_pledged_balance' : IDL.Func([IDL.Text], [Result_3], ['query']),
    'get_total_followers' : IDL.Func([IDL.Text], [IDL.Nat64], ['query']),
    'get_total_following' : IDL.Func([IDL.Text], [IDL.Nat64], ['query']),
    'get_total_pledged' : IDL.Func([IDL.Text, IDL.Text], [Result_3], ['query']),
    'get_total_pledged_and_expected' : IDL.Func(
        [IDL.Text, IDL.Text],
        [Result_9],
        ['query'],
      ),
    'get_user_active_pledges' : IDL.Func([IDL.Text], [Result_10], ['query']),
    'get_user_basic_information' : IDL.Func([IDL.Text], [Result_11], ['query']),
    'get_user_pledges_enriched' : IDL.Func([IDL.Text], [Result_12], ['query']),
    'get_user_profile_pic' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'get_user_real_balance' : IDL.Func([IDL.Text], [Result_3], []),
    'get_user_reputation' : IDL.Func([IDL.Principal], [Result_3], ['query']),
    'get_user_total_pledges' : IDL.Func([IDL.Text], [Result_10], ['query']),
    'get_user_username' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'pledge_create' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat64, IDL.Vec(IDL.Nat8)],
        [IDL.Text],
        [],
      ),
    'query_scheduled_tasks_state' : IDL.Func([], [IDL.Text], ['query']),
    'reverse_approval' : IDL.Func([IDL.Text], [Result_2], []),
    'send_single_notification' : IDL.Func(
        [IDL.Text, IDL.Text, Notification],
        [Result_2],
        [],
      ),
    'start_scheduled_tasks' : IDL.Func([], [IDL.Text], []),
    'stop_scheduled_tasks' : IDL.Func([], [IDL.Text], []),
    'trigger_delete_orphan_ideas' : IDL.Func([], [Result_2], []),
    'trigger_delete_orphan_solutions' : IDL.Func([], [Result_2], []),
    'trigger_delete_unused_images' : IDL.Func([], [Result_2], []),
    'upload_image' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8), IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'validate_user_balance_or_delete_pledge' : IDL.Func(
        [IDL.Text, IDL.Nat64, IDL.Text],
        [Result_2],
        [],
      ),
    'verify_transaction_details' : IDL.Func(
        [IDL.Nat64, IDL.Nat64, PaymentType],
        [Result_2],
        [],
      ),
    'withdraw_from_feature_subaccount' : IDL.Func(
        [IDL.Nat64, IDL.Text, IDL.Principal],
        [Result_3],
        [],
      ),
  });
};
export const init = ({ IDL }) => { return []; };